---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

- hosts: localhost
  become: no
  tasks:
    - name: Create SSH Keys
      block:
      - name: Check if SSH key exists
        stat:
          path: /home/{{ ansible_user_id }}/.ssh/id_ed25519
        register: ssh_key 
      - name: Generate SSH key
        shell: ssh-keygen -t ed25519 -C "{{ ansible_user_id }}" -N "" -f /home/{{ ansible_user_id }}/.ssh/id_ed25519
        when: ssh_key.stat.exists == False

- hosts: localhost
  become: no
  tasks:
    - name: Install and configure zsh
      block:
      - name: Install zsh
        become: yes
        apt:
          name: zsh
          state: present
      - name: Check if $ZSH folder exists
        stat:
          path: /home/{{ ansible_user_id }}/.oh-my-zsh
        register: zsh_folder
      - name: Install oh-my-zsh 
        shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        when: zsh_folder.stat.exists == False
      - name: Set zsh as default shell
        become: yes
        user:
          name: "{{ ansible_user_id }}"
          shell: /usr/bin/zsh
      - name: Copy zshrc file
        copy:
          src: files/.zshrc
          dest: /home/{{ ansible_user_id }}/.zshrc
      - name: Change owner and permissions of .zshrc
        ansible.builtin.file:
          path: /home/{{ ansible_user_id }}/.zshrc
          owner: "{{ ansible_user_id }}"
          mode: 0644

- hosts: localhost
  become: no
  tasks:
    - name: Install and configure Vim
      block:
      - name: See if .vim_runtime exists
        stat:
          path: /home/{{ ansible_user_id }}/.vim_runtime
        register: vim_folder
      - name: Configure Vim
        shell:
          cmd: |
            git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime && sh ~/.vim_runtime/install_awesome_vimrc.sh
        when: vim_folder.stat.exists == False