name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: ./setup_dependencies.sh

      - name: Run ansible playbook
        run: ansible-playbook playbook.yml